#!/bin/bash

ID="${1}"

if [[ "${ID}" =~ ^(|-h|--help)$ ]]; then
    echo -e "Usage:"
    echo -e "\t${0} <task-id> | <nvr>"
    exit 0
fi

LOGS="${PWD}/${ID}"

if [[ "${ID}" =~ ^[0-9]+$ ]]; then
    ID_OPT="${ID}"
else
    ID_OPT="--nvr ${ID}"
fi

if [[ "$0" =~ brew- ]]; then
    koji=brew
else
    koji=$(echo "$0" | egrep -o '(arm|s390|ppc)-')koji
fi

$koji download-logs -c --recurse --dir=${LOGS} --match=build.log ${ID_OPT}

for LOG in $(find ${LOGS} -name build.log); do
    {
        export IFS=""
        NVR=$(egrep -m1 '^Wrote:' ${LOG} | sed -e 's|.*/||' -e 's|.src.rpm||')
        ARCH=$(egrep -m1 '^Building for target' ${LOG} | sed 's/.* //')
        OUTDIR="${NVR}-${ID}/${ARCH}"
        echo >&2 "Processing log ${LOG} for arch ${ARCH}"
        mkdir -p "${OUTDIR}"
        while read LINE; do
            [[ "${LINE}" =~ \[\ fail\ \]$ ]] || continue
            TEST=${LINE/ */}
            while ! [[ "${LINE}" =~ ^\ -\  ]]; do
                echo "${LINE}"
                read LINE || break
            done > "${OUTDIR}/${TEST}"
        done < ${LOG}
    } &
done; wait

